from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime


def generate_report(scores, feedbacks, username="User", filename="report.pdf"):

    try:
        doc = SimpleDocTemplate(filename)
        styles = getSampleStyleSheet()

        content = []

        # -----------------------------
        # HEADER
        # -----------------------------
        content.append(Paragraph("AI Interview Report", styles["Title"]))
        content.append(Spacer(1, 10))

        content.append(Paragraph(f"Candidate: {username}", styles["Normal"]))
        content.append(Paragraph(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", styles["Normal"]))
        content.append(Spacer(1, 15))

        # -----------------------------
        # SCORE SUMMARY
        # -----------------------------
        avg_score = sum(scores) / len(scores) if scores else 0

        content.append(Paragraph(f"Average Score: {avg_score:.2f}/10", styles["Heading2"]))
        content.append(Spacer(1, 10))

        # -----------------------------
        # FEEDBACK SECTION
        # -----------------------------
        for i, fb in enumerate(feedbacks):
            content.append(Paragraph(f"Question {i+1}", styles["Heading3"]))
            content.append(Paragraph(fb, styles["BodyText"]))
            content.append(Spacer(1, 12))

        # -----------------------------
        # FOOTER
        # -----------------------------
        content.append(Spacer(1, 20))
        content.append(Paragraph("Generated by AI Career Assistant", styles["Italic"]))

        doc.build(content)

        return filename

    except Exception as e:
        print("Error generating report:", e)
        return None